spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordermeal?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    #需要配置商密码 password
    driver-class-name: com.mysql.cj.jdbc.Driver