package com.heaiai.own.ordermeal.dao;

import com.heaiai.own.ordermeal.entity.TestDTO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TestMapper {

    List<TestDTO> getList(TestDTO params);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    int insert(TestDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    int insertSelective(TestDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    TestDTO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(TestDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    int updateByPrimaryKey(TestDTO record);
}