package com.heaiai.own.ordermeal.entity;

import java.util.Date;

public class TestDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.id
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.user_code
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.age
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.create_date
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.id
     *
     * @return the value of t_test.id
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.id
     *
     * @param id the value for t_test.id
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.user_code
     *
     * @return the value of t_test.user_code
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.user_code
     *
     * @param userCode the value for t_test.user_code
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.age
     *
     * @return the value of t_test.age
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.age
     *
     * @param age the value for t_test.age
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.create_date
     *
     * @return the value of t_test.create_date
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.create_date
     *
     * @param createDate the value for t_test.create_date
     *
     * @mbg.generated Tue Jul 21 10:42:17 GMT+08:00 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}